{"url":"https://github.com/yuzu-emu-mirror/.archive.git","type":"git","repo":"yuzu-archives","private":true,"paused":true}
{"url":"https://https.git.savannah.gnu.org/git/nano.git","type":"git","repo":"nano"}
{"url":"https://codeberg.org/ums9230-mainline/libcamera.git","type":"git","repo":"ums9230-mainline-libcamera"}
{"url":"git://linux-libre.fsfla.org/releases.git","type":"git","repo":"linux-libre"}
{"url":"https://repo.dec05eba.com/phoenix","type":"git","repo":"phoenix"}
{"url":"https://github.com/yuzu-emu-mirror/FasTC.git","type":"git","repo":"yuzu-FasTC","private":true,"paused":true}
{"url":"https://gitlab.com/echo-pmos/amazon-checkers-kernel.git","type":"git","repo":"echo-pmos-amazon-checkers-kernel"}
{"url":"https://https.git.savannah.gnu.org/git/cpio.git","type":"git","repo":"cpio"}
{"url":"https://github.com/yuzu-emu-mirror/ext-linux-bin.git","type":"git","repo":"yuzu-ext-linux-bin","private":true,"paused":true}
